### ISSUE TITLE
Create and style author follow-up page

### ISSUE THREAD

**Issue by luizguilherme5** [translate-me/frontend#36]
## Description

This issue intends to implement the screen to author follow his translations request and get updates about translation status

## Acceptance Criteria

- [ ] Screen Implemented should be according with prototype (prototype must be enhanced)
- [ ] There should be a screen that welcome the new come user and explain the project
- [ ] This page must be static with the platform benefits
- [ ] The screen should follow the patters according the style guide

## Screen Prototype
![image.png](https://images.zenhubusercontent.com/58d523f251aa2c3057796454/658afcd3-8e40-4b69-9ddd-c86912d1d88b)

**Comment by joaorobson** [comment]
This issue is already implemented in the [FollowTranslation](https://github.com/translate-me/frontend/blob/devel/frontend/src/Screens/FollowTranslations.js) component.
